; NC200 hardware stuff.

PORT_DISPLAY_MEMORY_ADDR    = 0x00
PORT_BANK0                  = 0x10
PORT_BANK1                  = 0x11
PORT_BANK2                  = 0x12
PORT_BANK3                  = 0x13
PORT_WAIT_STATE_CONTROL     = 0x20
PORT_BAUDRATE               = 0x30
PORT_PRINTER_DATA           = 0x40
PORT_SPEAKER                = 0x50
PORT_IRQ_MASK               = 0x60
PORT_ONOFF_CONTROL          = 0x70
PORT_PRINTER_STATUS         = 0x80
PORT_IRQ_STATUS             = 0x90
PORT_BATTERY_STATUS         = 0xa0
PORT_KEYBOARD               = 0xb0
PORT_PD71051                = 0xc0
PORT_MC146818_ADDRESS       = 0xd0
PORT_MC146818_DATA          = 0xd1
PORT_NEC765_STATUS          = 0xe0
PORT_NEC765_DATA            = 0xe1
